package razaswow;

import java.io.File;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author elram
 */
public class RazasWoWindow extends javax.swing.JFrame {

    RazasWowJaxB gesJAXB = new RazasWowJaxB();
    RazasWowDOM gesDOM = new RazasWowDOM();
    RazasWowQuery gesQuery = new RazasWowQuery();
    public static File fileXML = new File("documentos/razasWoW.xml");

    public RazasWoWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrameAddRace = new javax.swing.JFrame();
        jTextFieldExpansion = new javax.swing.JTextField();
        jLabelYear = new javax.swing.JLabel();
        jTextFieldYear = new javax.swing.JTextField();
        jLabelZone = new javax.swing.JLabel();
        jTextFieldZone = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelFaction = new javax.swing.JLabel();
        jTextFieldFaction = new javax.swing.JTextField();
        jLabelOrigin = new javax.swing.JLabel();
        jTextFieldOrigin = new javax.swing.JTextField();
        jLabelLenguage = new javax.swing.JLabel();
        jTextFieldLenguage = new javax.swing.JTextField();
        jLabelCapital = new javax.swing.JLabel();
        jTextFieldCapital = new javax.swing.JTextField();
        jLabelLeader = new javax.swing.JLabel();
        jTextFieldLeader = new javax.swing.JTextField();
        jLabelMount = new javax.swing.JLabel();
        jTextFieldMount = new javax.swing.JTextField();
        jButtonCancelAdd = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jLabelExpansion = new javax.swing.JLabel();
        jButtonShow = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaShowed = new javax.swing.JTextArea();
        jLabelChangeField = new javax.swing.JLabel();
        jLabelOldField = new javax.swing.JLabel();
        jTextFieldOldField = new javax.swing.JTextField();
        jTextFieldNewField = new javax.swing.JTextField();
        jButtonInfo = new javax.swing.JButton();
        jLabelNewField = new javax.swing.JLabel();
        jComboBoxFieldList = new javax.swing.JComboBox<>();
        jButtonChangeField = new javax.swing.JButton();
        jButtonSwapFrame = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxQuery = new javax.swing.JComboBox<>();
        jButtonQuery = new javax.swing.JButton();

        jFrameAddRace.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jFrameAddRace.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                jFrameAddRaceWindowClosed(evt);
            }
        });

        jLabelYear.setText("Año de introducción");

        jLabelZone.setText("Zona Inicial");

        jLabelName.setText("Nombre");

        jLabelFaction.setText("Facción");

        jLabelOrigin.setText("Origen");

        jLabelLenguage.setText("Idioma");

        jLabelCapital.setText("Capital");

        jLabelLeader.setText("Líder");

        jLabelMount.setText("Montura");

        jButtonCancelAdd.setText("Cancelar");
        jButtonCancelAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelAddActionPerformed(evt);
            }
        });

        jButtonAdd.setText("Añadir");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jLabelExpansion.setText("Expansión en la que ha sido introducida la raza");

        javax.swing.GroupLayout jFrameAddRaceLayout = new javax.swing.GroupLayout(jFrameAddRace.getContentPane());
        jFrameAddRace.getContentPane().setLayout(jFrameAddRaceLayout);
        jFrameAddRaceLayout.setHorizontalGroup(
            jFrameAddRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameAddRaceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jFrameAddRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldExpansion)
                    .addComponent(jLabelYear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldYear, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelZone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldZone, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelFaction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldFaction)
                    .addComponent(jLabelOrigin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldOrigin)
                    .addComponent(jLabelLenguage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLenguage, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelCapital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCapital)
                    .addComponent(jLabelLeader, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldLeader)
                    .addComponent(jLabelMount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldMount, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jFrameAddRaceLayout.createSequentialGroup()
                        .addComponent(jButtonCancelAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(jButtonAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrameAddRaceLayout.createSequentialGroup()
                        .addComponent(jLabelExpansion)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jFrameAddRaceLayout.setVerticalGroup(
            jFrameAddRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrameAddRaceLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelExpansion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldExpansion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelYear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelZone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFaction)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldFaction, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelOrigin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLenguage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLenguage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelCapital)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCapital, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelLeader)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldLeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelMount)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldMount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jFrameAddRaceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCancelAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jButtonAdd, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonShow.setText("Mostrar");
        jButtonShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowActionPerformed(evt);
            }
        });

        jTextAreaShowed.setEditable(false);
        jTextAreaShowed.setColumns(20);
        jTextAreaShowed.setRows(5);
        jScrollPane1.setViewportView(jTextAreaShowed);

        jLabelChangeField.setText("Cambiar Campo");

        jLabelOldField.setText("Nombre del campo antiguo");

        jTextFieldOldField.setEnabled(false);

        jTextFieldNewField.setEnabled(false);

        jButtonInfo.setText("Info");
        jButtonInfo.setEnabled(false);
        jButtonInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInfoActionPerformed(evt);
            }
        });

        jLabelNewField.setText("Nombre del nuevo campo");

        jComboBoxFieldList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Raza", "Humano", "Orco", "Enano", "No-Muerto", "Elfo de la Noche", "Tauren", "Gnomo", "Trol", "Draenei", "Elfo de la Sangre", "Huargen", "Goblin", "Pandaren" }));
        jComboBoxFieldList.setEnabled(false);
        jComboBoxFieldList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFieldListActionPerformed(evt);
            }
        });

        jButtonChangeField.setText("Cambiar");
        jButtonChangeField.setEnabled(false);
        jButtonChangeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeFieldActionPerformed(evt);
            }
        });

        jButtonSwapFrame.setText("Añadir Raza");
        jButtonSwapFrame.setEnabled(false);
        jButtonSwapFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSwapFrameActionPerformed(evt);
            }
        });

        jLabel1.setText("Hacer una consulta");

        jComboBoxQuery.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona una consulta", "Nombre de las razas", "Razas de la Alianza", "Razas de la Horda" }));
        jComboBoxQuery.setEnabled(false);

        jButtonQuery.setText("Realizar consulta");
        jButtonQuery.setEnabled(false);
        jButtonQuery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonQueryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelChangeField)
                                .addGap(42, 42, 42)
                                .addComponent(jButtonInfo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldOldField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelOldField, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jComboBoxFieldList, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextFieldNewField)
                                    .addComponent(jLabelNewField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonChangeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBoxQuery, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonQuery)))
                        .addComponent(jButtonShow, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jButtonSwapFrame, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 495, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonShow)
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelChangeField)
                            .addComponent(jButtonInfo))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelOldField)
                            .addComponent(jLabelNewField))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldOldField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNewField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxFieldList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonChangeField))
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBoxQuery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonQuery))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSwapFrame)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowActionPerformed
        if (RazasWowSAX.openFile(fileXML) == true) {
            this.jTextAreaShowed.setText(RazasWowSAX.runSAX());
            jButtonInfo.setEnabled(true);
            jButtonChangeField.setEnabled(rootPaneCheckingEnabled);
            jButtonSwapFrame.setEnabled(true);
            
            jTextFieldOldField.setEnabled(true);
            jTextFieldNewField.setEnabled(true);

            jComboBoxFieldList.removeAll();
            jComboBoxFieldList.addItem("Seleccionar Raza");
            RazasWowSAX.saxHandler.comboArray.forEach((string) -> {
                jComboBoxFieldList.addItem(string);
            });
                    
            jComboBoxFieldList.setEnabled(true);
            jButtonQuery.setEnabled(true);
            jComboBoxQuery.setEnabled(true);
        } else {
            JOptionPane.showMessageDialog(null, "Error al abrir el archivo :(", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonShowActionPerformed

    private void jButtonInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInfoActionPerformed
        JOptionPane.showMessageDialog(null, "Puedes modificar: FacciÃ³n de la raza, Capital de la raza y LÃ­der de la raza", "INFO", JOptionPane.ERROR_MESSAGE);
    }//GEN-LAST:event_jButtonInfoActionPerformed

    private void jComboBoxFieldListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFieldListActionPerformed


    }//GEN-LAST:event_jComboBoxFieldListActionPerformed

    private void jButtonChangeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeFieldActionPerformed
        if (gesJAXB.openJaxB(fileXML) == true) {
            if (jTextFieldOldField.getText().equals("") || jTextFieldNewField.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "¡Rellena los campos!", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
            if (jComboBoxFieldList.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(null, "¡Seleccione una raza!", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                if (gesJAXB.changeJaxB(jComboBoxFieldList.getSelectedItem().toString(), jTextFieldOldField.getText(), jTextFieldNewField.getText()) == true) {
                    this.jTextAreaShowed.setText(RazasWowSAX.runSAX());
                } else {
                    JOptionPane.showMessageDialog(null, "Error al cambiar campos", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error al abrir el archivo :(", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonChangeFieldActionPerformed

    private void jButtonSwapFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSwapFrameActionPerformed
        jFrameAddRace.setSize(350, 800);
        jFrameAddRace.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonSwapFrameActionPerformed

    private void jFrameAddRaceWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jFrameAddRaceWindowClosed
        this.setVisible(true);
        removeText();
    }//GEN-LAST:event_jFrameAddRaceWindowClosed

    private void jButtonCancelAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelAddActionPerformed
        jFrameAddRace.dispose();
        removeText();
        this.setVisible(true);
    }//GEN-LAST:event_jButtonCancelAddActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        String name = jTextFieldName.getText();
        String faction = jTextFieldFaction.getText();
        String origin = jTextFieldOrigin.getText();
        String lenguage = jTextFieldLenguage.getText();
        String capital = jTextFieldCapital.getText();
        String leader = jTextFieldLeader.getText();
        String mount = jTextFieldMount.getText();
        String expansion = jTextFieldExpansion.getText();
        String year = jTextFieldYear.getText();
        String zone = jTextFieldZone.getText();
        if (gesDOM.openDOM(fileXML) == true) {
            if (checkText() == false) {
                JOptionPane.showMessageDialog(null, "¡Rellena todos los campos!", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else if (gesDOM.addDOM(name, faction, origin, lenguage, capital, leader, mount, expansion, year, zone)) {
                if (gesDOM.saveDOM()) {
                    jFrameAddRace.dispose();
                } else {
                    JOptionPane.showMessageDialog(null, "Error al añadir raza", "ERROR", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Bruh", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonQueryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonQueryActionPerformed
        if (jComboBoxQuery.getSelectedIndex() == 0) {
            if (gesQuery.openXPath(fileXML)) {
                JOptionPane.showMessageDialog(null, "Selecciona una consulta", "ERROR", JOptionPane.ERROR_MESSAGE);
            }
        } else if (jComboBoxQuery.getSelectedIndex() == 1) {
            if (gesQuery.openXPath(fileXML)) {
                jTextAreaShowed.setText("Nombres de raza: \n" + gesQuery.executeXPath("//Nombre"));
            }
        } else if (jComboBoxQuery.getSelectedIndex() == 2) {
            if (gesQuery.openXPath(fileXML)) {
                jTextAreaShowed.setText("Razas de la Alianza: \n" + gesQuery.executeXPath("/Razas/Raza[Bando='Alianza']/Nombre"));
            }
        } else if (jComboBoxQuery.getSelectedIndex() == 3) {
            if (gesQuery.openXPath(fileXML)) {
                jTextAreaShowed.setText("Razas de la Horda: \n" + gesQuery.executeXPath("/Razas/Raza[Bando='Horda']/Nombre"));
            }
        } else {
            JOptionPane.showMessageDialog(null, "Error en la consulta", "ERROR", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jButtonQueryActionPerformed
    public void removeText() {
        jTextFieldExpansion.setText("");
        jTextFieldYear.setText("");
        jTextFieldZone.setText("");
        jTextFieldName.setText("");
        jTextFieldFaction.setText("");
        jTextFieldOrigin.setText("");
        jTextFieldLenguage.setText("");
        jTextFieldCapital.setText("");
        jTextFieldLeader.setText("");
        jTextFieldMount.setText("");
    }

    public boolean checkText() {
        return !(jTextFieldName.getText().equals("") || jTextFieldFaction.getText().equals("") || jTextFieldOrigin.getText().equals("")
                || jTextFieldLenguage.getText().equals("") || jTextFieldCapital.getText().equals("") || jTextFieldLeader.getText().equals("")
                || jTextFieldMount.getText().equals("") || jTextFieldExpansion.getText().equals("") || jTextFieldYear.getText().equals("")
                || jTextFieldZone.getText().equals(""));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RazasWoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new RazasWoWindow().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancelAdd;
    private javax.swing.JButton jButtonChangeField;
    private javax.swing.JButton jButtonInfo;
    private javax.swing.JButton jButtonQuery;
    private javax.swing.JButton jButtonShow;
    private javax.swing.JButton jButtonSwapFrame;
    private javax.swing.JComboBox<String> jComboBoxFieldList;
    private javax.swing.JComboBox<String> jComboBoxQuery;
    private javax.swing.JFrame jFrameAddRace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCapital;
    private javax.swing.JLabel jLabelChangeField;
    private javax.swing.JLabel jLabelExpansion;
    private javax.swing.JLabel jLabelFaction;
    private javax.swing.JLabel jLabelLeader;
    private javax.swing.JLabel jLabelLenguage;
    private javax.swing.JLabel jLabelMount;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNewField;
    private javax.swing.JLabel jLabelOldField;
    private javax.swing.JLabel jLabelOrigin;
    private javax.swing.JLabel jLabelYear;
    private javax.swing.JLabel jLabelZone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaShowed;
    private javax.swing.JTextField jTextFieldCapital;
    private javax.swing.JTextField jTextFieldExpansion;
    private javax.swing.JTextField jTextFieldFaction;
    private javax.swing.JTextField jTextFieldLeader;
    private javax.swing.JTextField jTextFieldLenguage;
    private javax.swing.JTextField jTextFieldMount;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNewField;
    private javax.swing.JTextField jTextFieldOldField;
    private javax.swing.JTextField jTextFieldOrigin;
    private javax.swing.JTextField jTextFieldYear;
    private javax.swing.JTextField jTextFieldZone;
    // End of variables declaration//GEN-END:variables
}
